name: dbsimilarity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit>=2024         # conda-forge build
  - numpy<2.4           # matches rdkit/scipy stack
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - networkx
  - pip
  - pip:
      - streamlit>=1.38
      - plotly
      - mordred
      - xlsxwriter
      - mpld3
