name: dbsimilarity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit>=2025.09
  - pandas>=2.3
  - numpy>=1.26
  - scikit-learn>=1.5
  - scipy>=1.12
  - matplotlib>=3.8
  - networkx>=3.2
  - plotly>=5.20
  - pillow
  - xlsxwriter
  - pip
  - pip:
      - mordred
      - mpld3  # if you want interactive dendrogram export
      # (streamlit is preinstalled on Streamlit Cloud; include it locally if needed)
