name: dbsimilarity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit=2025.09.1
  - numpy=1.26
  - pandas=2.3
  - scipy=1.16
  - scikit-learn=1.7
  - matplotlib=3.10
  - pip
  - pip:
      - streamlit==1.50.0
      - plotly==6.3.1
      - mordred==1.2.0
      - networkx==3.5
      - pillow==11.3.0
      - xlsxwriter==3.2.9
      - pyarrow==22.0.0
