name: dbsimilarity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit=2025.09.1
  - numpy>=1.26,<3
  - pandas>=2.1,<3
  - scikit-learn
  - scipy
  - matplotlib
  - networkx
  - pillow
  - pyarrow
  - pip
  - pip:
      - streamlit>=1.38
      - plotly
      - mordred
      - xlsxwriter
