name: dbsimilarity
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit=2025.09.1
  - numpy=1.26.*
  - pandas=2.3.*
  - scikit-learn=1.7.*
  - scipy=1.16.*
  - matplotlib=3.10.*
  - pillow
  - pip
  - pip:
      - streamlit>=1.38
      - plotly
      - networkx
      - mordred
      - xlsxwriter
