name: dbsimilarity-st
channels:
  - conda-forge
dependencies:
  - python=3.11
  - streamlit>=1.38
  - rdkit  # from conda-forge (current builds like 2025.09.1 are fine)
  - pandas>=2.1
  - numpy>=1.26
  - scikit-learn
  - scipy
  - matplotlib
  - plotly
  - networkx
  - pillow
  - xlsxwriter
  - pyarrow
  - pip
  - pip:
      - mordred==1.2.0  # pip-only
